image: node:latest

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install

test:
  stage: test
  script:
    - cat package.json
    - npm run test
    - npm run build

deploy:
  stage: deploy
  script:
    - npm run build
